apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres/postgres-service.yaml
  - postgres/postgres-secrets.yaml
  - postgres/postgres-storage.yaml
  - postgres/postgres.yaml