apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          env:
            - name: BACKEND_URL
              value: "http://backstage-service.backstage.svc.cluster.local:7007"