apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage 
spec:
  selector:
    app: backstage
  ports:
  - name: http
    port: 80
    targetPort: 7007
    protocol: TCP